language: ruby
rvm:
  - 2.3.0

before_install:
  - sudo apt-get install whiptail
  - gem install bundler -v '~> 1.11'
script: bundle exec rake test

addons:
  code_climate:
    repo_token: 0de11deef0069410946fee3803356da392661dd3407cf1d5b57d4939fbfa1167
